const fs = require('fs');
const path = require('path');

function normalizeName(name) {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '');
}

const imagesDir = path.join(__dirname, '../../../public/images');
const outputPath = path.join(__dirname, '../../../data/personaImageMap.js');

const imageMap = {};

fs.readdirSync(imagesDir).forEach((file) => {
  if (file.startsWith('P5X_') && file.endsWith('.png')) {
    const rawName = file.replace(/^P5X_/, '').replace(/\.png$/, '').replace(/_/g, ' ');
    const key = rawName;
    imageMap[key] = `/images/${file}`;
  }
});

const fileContent =
  `// Auto-generated by generateImageMap.js\n` +
  `const personaImageMap = ${JSON.stringify(imageMap, null, 2)};\n\n` +
  `export default personaImageMap;\n`;

fs.writeFileSync(outputPath, fileContent);
console.log('✅ Generated personaImageMap.js');